version: 2
jobs:
  build:
    steps:
      - checkout
      - run: docker login -e="." -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - run:
           IMAGE_TAG=ajslater/nginx
           docker build -t $IMAGE_TAG .
      - run:
          TAG=$IMAGE_TAG:$(echo $CIRCLE_SHA1 | head -c 7)
          docker tag ajslater/nginx $TAG
          docker push $TAG
