executors:
  latest-machine:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  build:
    environment:
      BUILDX_NO_DEFAULT_LOAD: 1
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: ./install-binfmt-platforms.sh
          name: Install binfmt Platforms
      - run:
          command: ./build-multiarch.sh
          name: Build
  deploy:
    environment:
      PUSH: "--push"
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
          name: Login to Docker Hub
      - run:
          command: ./install-binfmt-platforms.sh
          name: Install binfmt Platforms
      - run:
          command: ./build-multiarch.sh
          name: Build & Push
version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - master
                - main
  version: 2.1
