jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: ./build.sh
          name: Build Nginx
      - run:
          command: ./ci/save-images.sh
          name: Archive Docker image
      - persist_to_workspace:
          paths:
            - ./images
          root: .
  deploy:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./ci/load-images.sh
          name: Load saved Docker images
      - run:
          command: ./ci/tag-and-push.sh
          name: Publish Docker Image to Docker Hub
version: 2.1
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
                - main
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - master
                - main
          requires:
            - build
  version: 2.1
