version: 2
jobs:
  build:
    branches:
      only: master
    machine: true
    environment:
        IMAGE: ajslater/nginx
    steps:
      - checkout
      - run: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - run:
            VERSION=$(cat VERSION)
            docker build -t $IMAGE --build-arg $VERSION .
      - run:
            VERSION=$(cat VERSION)
            TAG=$VERSION-$(echo $CIRCLE_SHA1 | head -c 7);
            docker tag $IMAGE $IMAGE:$TAG;
            docker push $IMAGE:$TAG;
      - run:
            docker tag $IMAGE $IMAGE:latest;
            docker push $IMAGE:latest
