executors:
  latest-machine:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  build:
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: ./build.sh
          name: Build
  deploy:
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: DEPLOY=1 ./build.sh
          name: Build & Deploy
version: 2.1
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - master
                - main
  version: 2.1
