version: 2
jobs:
  build:
    branches:
      only: master
    machine: true
    environment:
        IMAGE_TAG: ajslater/nginx
    steps:
      - checkout
      - run: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - run: docker build -t $IMAGE_TAG .
      - run:
            TAG=$IMAGE_TAG:$(echo $CIRCLE_SHA1 | head -c 7);
            docker tag $IMAGE_TAG $TAG;
            docker push $TAG
